One-Hot Encoding is a technique used to convert categorical data (text labels or categories) into a binary numerical format so machine learning algorithms can process it.

How It Works
It creates a new binary column (containing 0 or 1) for every unique category present in the dataset. For each data row, a 1 is assigned to the column representing its category, and 0 is assigned to all other columns.

Example:
Converting a "Color" column with values Red, Green, and Blue:

In [1]:
import pandas as pd

d = {'sales': [100000,222000,1000000,522000,111111,222222,1111111,20000,75000,90000,1000000,10000],
'city': ['Tampa','Tampa','Orlando','Jacksonville','Miami','Jacksonville','Miami','Miami','Orlando','Orlando','Orlando','Orlando'],
'size': ['Small', 'Medium','Large','Large','Small','Medium','Large','Small','Medium','Medium','Medium','Small',]}

In [2]:
df_ohe = pd.DataFrame(data = d)

df_ohe.head()

     sales          city    size
0   100000         Tampa   Small
1   222000         Tampa  Medium
2  1000000       Orlando   Large
3   522000  Jacksonville   Large
4   111111         Miami   Small

In [3]:
df_ohe['city'].unique

<bound method Series.unique of 0            Tampa
1            Tampa
2          Orlando
3     Jacksonville
4            Miami
5     Jacksonville
6            Miami
7            Miami
8          Orlando
9          Orlando
10         Orlando
11         Orlando
Name: city, dtype: str>

In [4]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder(handle_unknown='ignore', sparse_output=False).set_output(transform='pandas')

In [5]:
ohetransform = ohe.fit_transform(df_ohe[['city']])

In [6]:
ohetransform

    city_Jacksonville  city_Miami  city_Orlando  city_Tampa
0                 0.0         0.0           0.0         1.0
1                 0.0         0.0           0.0         1.0
2                 0.0         0.0           1.0         0.0
3                 1.0         0.0           0.0         0.0
4                 0.0         1.0           0.0         0.0
5                 1.0         0.0           0.0         0.0
6                 0.0         1.0           0.0         0.0
7                 0.0         1.0           0.0         0.0
8                 0.0         0.0           1.0         0.0
9                 0.0         0.0           1.0         0.0
10                0.0         0.0           1.0         0.0
11                0.0         0.0           1.0         0.0

In [7]:
df_ohe = pd.concat([df_ohe, ohetransform], axis=1)

df_ohe = df_ohe.drop(columns=['city'])

In [8]:
df_ohe.head()

     sales    size  city_Jacksonville  city_Miami  city_Orlando  city_Tampa
0   100000   Small                0.0         0.0           0.0         1.0
1   222000  Medium                0.0         0.0           0.0         1.0
2  1000000   Large                0.0         0.0           1.0         0.0
3   522000   Large                1.0         0.0           0.0         0.0
4   111111   Small                0.0         1.0           0.0         0.0