# Simple Imputer (Handle Missing Data)

Simple Imputer fills in missing values (NaN, None, or placeholders) in numerical or categorical columns using basic statistical strategies.

**How It Works:**

It calculates a summary statistic on non-missing data during fit() and replaces every NaN with that value during transform().

**Strategies & Concepts:**

mean: x_imputed = mean(column) (Numerical only)

median: x_imputed = median(column) (Numerical only, robust to outliers)

most_frequent: x_imputed = mode(column) (Categorical or numerical)

constant: x_imputed = fill_value (e.g., replace missing with -1 or "Missing")

**Best Use Cases:**

Baseline preprocessing for handling incomplete datasets before sending data into algorithms that cannot handle missing values.

In [2]:
import pandas as pd
import numpy as np

miles = pd.DataFrame({'farthest_run_mi':[50,62,np.nan,100,26,13,31,50]})

In [3]:
miles.isna()

   farthest_run_mi
0            False
1            False
2             True
3            False
4            False
5            False
6            False
7            False

In [4]:
from sklearn.impute import SimpleImputer

imp_mean = SimpleImputer(strategy='mean')

imp_mean.fit_transform(miles)

array([[ 50.        ],
       [ 62.        ],
       [ 47.42857143],
       [100.        ],
       [ 26.        ],
       [ 13.        ],
       [ 31.        ],
       [ 50.        ]])

In [5]:
imp_median = SimpleImputer(strategy='median')

imp_median.fit_transform(miles)

array([[ 50.],
       [ 62.],
       [ 50.],
       [100.],
       [ 26.],
       [ 13.],
       [ 31.],
       [ 50.]])

In [6]:
imp_mode = SimpleImputer(strategy='most_frequent')

imp_mode.fit_transform(miles)

array([[ 50.],
       [ 62.],
       [ 50.],
       [100.],
       [ 26.],
       [ 13.],
       [ 31.],
       [ 50.]])

In [7]:
imp_constant = SimpleImputer(strategy='constant', fill_value=13)

imp_constant.fit_transform(miles)

array([[ 50.],
       [ 62.],
       [ 13.],
       [100.],
       [ 26.],
       [ 13.],
       [ 31.],
       [ 50.]])

In [8]:
names = pd.DataFrame({'names':['messi','ronaldo','pele','maradona',np.nan,'neymar','kdb']})

names.isna()

   names
0  False
1  False
2  False
3  False
4   True
5  False
6  False

In [9]:
imp_constant_category = SimpleImputer(strategy='constant', fill_value = 'lewandowiski')

imp_constant_category.fit_transform(names)

array([['messi'],
       ['ronaldo'],
       ['pele'],
       ['maradona'],
       ['lewandowiski'],
       ['neymar'],
       ['kdb']], dtype=object)

**To show which rows have been imputed:**

In [10]:
imp_mean_marked = SimpleImputer(add_indicator=True)

imp_mean_marked.fit_transform(miles)

array([[ 50.        ,   0.        ],
       [ 62.        ,   0.        ],
       [ 47.42857143,   1.        ],
       [100.        ,   0.        ],
       [ 26.        ,   0.        ],
       [ 13.        ,   0.        ],
       [ 31.        ,   0.        ],
       [ 50.        ,   0.        ]])